import type { CommunityPresetCatalogEntry } from "@/lib/presets/community-preset-types";

export const COMMUNITY_PRESET_CATALOG: CommunityPresetCatalogEntry[] = [
  {
    slug: "morning-school-routine",
    type: "task",
    name: "Morning routine before school",
    description: "Popular caregiver board for wake-up through leaving for school.",
    coverSymbolId: "wake",
    coverPictogramId: 8988,
    profession: "caregiver",
    stepCount: 8,
    likeCount: 2140,
    favoriteCount: 892,
    dailyUserCount: 1240,
    useCount: 18600,
    payload: {
      taskTitle: "Morning routine before school",
      taskDescription: "Wake up, hygiene, breakfast, and pack before leaving.",
      stepTitles: [
        "Wake up",
        "Use the bathroom",
        "Brush teeth",
        "Get dressed",
        "Eat breakfast",
        "Pack backpack",
        "Put on shoes",
        "Leave for school",
      ],
    },
  },
  {
    slug: "brush-teeth-full",
    type: "task",
    name: "Brush teeth routine",
    description: "Detailed dental hygiene sequence used in clinics and homes.",
    coverSymbolId: "brush",
    coverPictogramId: 2326,
    profession: "caregiver",
    stepCount: 9,
    likeCount: 1680,
    favoriteCount: 740,
    dailyUserCount: 980,
    useCount: 14200,
    payload: {
      taskTitle: "Brush teeth",
      taskDescription: "Full tooth-brushing routine with rinse and cleanup.",
      stepTitles: [
        "Get toothbrush",
        "Get toothpaste",
        "Put toothpaste on brush",
        "Brush top teeth",
        "Brush bottom teeth",
        "Brush tongue",
        "Spit in sink",
        "Rinse mouth",
        "Put toothbrush away",
      ],
    },
  },
  {
    slug: "patient-visit-clinic",
    type: "task",
    name: "Patient clinic visit",
    description: "Shared by physicians and nurses for outpatient visits.",
    coverSymbolId: "talk",
    coverPictogramId: 3345,
    profession: "physician",
    stepCount: 6,
    likeCount: 1320,
    favoriteCount: 610,
    dailyUserCount: 720,
    useCount: 9800,
    payload: {
      taskTitle: "Patient visit",
      taskDescription: "Check in through follow-up at a clinic visit.",
      stepTitles: [
        "Check in",
        "Wait in waiting room",
        "See nurse",
        "See doctor",
        "Ask questions",
        "Plan follow-up",
      ],
    },
  },
  {
    slug: "classroom-morning-arrival",
    type: "task",
    name: "Classroom morning arrival",
    description: "Teacher-favorite board for the first 30 minutes of class.",
    coverSymbolId: "school",
    coverPictogramId: 3082,
    profession: "teacher",
    stepCount: 5,
    likeCount: 980,
    favoriteCount: 455,
    dailyUserCount: 540,
    useCount: 7200,
    payload: {
      taskTitle: "Classroom morning arrival",
      taskDescription: "Greet, settle in, and start the first activity.",
      stepTitles: [
        "Say hello",
        "Find your seat",
        "Listen to teacher",
        "Get materials ready",
        "Start activity",
      ],
    },
  },
  {
    slug: "evening-wind-down",
    type: "task",
    name: "Evening wind-down",
    description: "Bedtime sequence for families and residential care.",
    coverSymbolId: "wake",
    coverPictogramId: 2280,
    profession: "caregiver",
    stepCount: 5,
    likeCount: 890,
    favoriteCount: 402,
    dailyUserCount: 610,
    useCount: 6500,
    payload: {
      taskTitle: "Evening wind-down",
      taskDescription: "Brush teeth, pajamas, story, and lights out.",
      stepTitles: ["Brush teeth", "Put on pajamas", "Read a story", "Lights out", "Good night"],
    },
  },
  {
    slug: "hand-washing-routine",
    type: "task",
    name: "Hand washing routine",
    description: "Health and school settings — before meals and after bathroom.",
    coverSymbolId: "brush",
    coverPictogramId: 2912,
    stepCount: 5,
    likeCount: 760,
    favoriteCount: 318,
    dailyUserCount: 890,
    useCount: 11200,
    payload: {
      taskTitle: "Wash hands",
      taskDescription: "Wet, soap, scrub, rinse, and dry.",
      stepTitles: [
        "Turn on water",
        "Wet hands",
        "Add soap",
        "Scrub hands",
        "Rinse and dry",
      ],
    },
  },
  {
    slug: "need-help-now",
    type: "communication",
    name: "I need help",
    description: "Quick phrase when someone needs assistance right away.",
    coverSymbolId: "help",
    coverPictogramId: 4570,
    tileCount: 2,
    likeCount: 2450,
    favoriteCount: 1102,
    dailyUserCount: 1580,
    useCount: 22400,
    payload: {
      tiles: [
        { label: "Help", symbolId: "help", pictogramId: 4570 },
        { label: "Wait", symbolId: "wait", pictogramId: 8109 },
      ],
    },
  },
  {
    slug: "hurt-need-help",
    type: "communication",
    name: "I'm in pain",
    description: "Clinical and home care — report discomfort and ask for help.",
    coverSymbolId: "help",
    coverPictogramId: 5484,
    profession: "physician",
    tileCount: 2,
    likeCount: 1890,
    favoriteCount: 860,
    dailyUserCount: 940,
    useCount: 13100,
    payload: {
      tiles: [
        { label: "Hurt", symbolId: "help", pictogramId: 5484 },
        { label: "Help", symbolId: "help", pictogramId: 4570 },
      ],
    },
  },
  {
    slug: "hungry-eat",
    type: "communication",
    name: "I'm hungry",
    description: "Mealtime request used across homes and classrooms.",
    coverSymbolId: "eat",
    coverPictogramId: 2349,
    tileCount: 2,
    likeCount: 1420,
    favoriteCount: 620,
    dailyUserCount: 870,
    useCount: 9800,
    payload: {
      tiles: [
        { label: "Eat", symbolId: "eat", pictogramId: 2349 },
        { label: "More", symbolId: "eat", pictogramId: 5508 },
      ],
    },
  },
  {
    slug: "bathroom-please",
    type: "communication",
    name: "Bathroom please",
    description: "Urgent bathroom request — high daily use in care settings.",
    coverSymbolId: "bathroom",
    coverPictogramId: 5921,
    tileCount: 1,
    likeCount: 1760,
    favoriteCount: 790,
    dailyUserCount: 1320,
    useCount: 18900,
    payload: {
      tiles: [{ label: "Bathroom", symbolId: "bathroom", pictogramId: 5921 }],
    },
  },
  {
    slug: "yes-ready-go",
    type: "communication",
    name: "Yes, I'm ready",
    description: "Confirm readiness before transitions and outings.",
    coverSymbolId: "check",
    coverPictogramId: 5583,
    tileCount: 2,
    likeCount: 980,
    favoriteCount: 410,
    dailyUserCount: 650,
    useCount: 7600,
    payload: {
      tiles: [
        { label: "Yes", symbolId: "check", pictogramId: 5583 },
        { label: "Go", symbolId: "walk", pictogramId: 3251 },
      ],
    },
  },
  {
    slug: "thank-you-greeting",
    type: "communication",
    name: "Thank you & hello",
    description: "Social phrase for greetings and gratitude.",
    coverSymbolId: "thank",
    coverPictogramId: 8129,
    profession: "teacher",
    tileCount: 2,
    likeCount: 870,
    favoriteCount: 380,
    dailyUserCount: 520,
    useCount: 6900,
    payload: {
      tiles: [
        { label: "Hello", symbolId: "talk", pictogramId: 6009 },
        { label: "Thanks", symbolId: "thank", pictogramId: 8129 },
      ],
    },
  },
  {
    slug: "water-thirsty",
    type: "communication",
    name: "I want water",
    description: "Drink request — one of the most used communication presets.",
    coverSymbolId: "water",
    coverPictogramId: 2248,
    tileCount: 2,
    likeCount: 1560,
    favoriteCount: 702,
    dailyUserCount: 1180,
    useCount: 16200,
    payload: {
      tiles: [
        { label: "Water", symbolId: "water", pictogramId: 2248 },
        { label: "Please", symbolId: "star", pictogramId: 8194 },
      ],
    },
  },
];
